code = """
/* Generated by generate_maps.py. DO NOT EDIT */
#background {
 fill: #e8f9fb;
 stroke: none;
},
#world {
 fill: #f5f3f2;
 stroke: none;
},
#graticule {
 stroke-width: 0.3px;
},
#zipcodes {
 fill: #FFF;
 stroke: #882222;
 stroke-width: 0.5px;
 stroke-opacity: 0.4;
},
#zipcodes-label {
 font-family: Arial;
 font-size: 13px;
},
#depth {
 stroke: #223366;
 stroke-width: 0.5px;
 stroke-opacity: 0.4;
},
#trees {
  fill: #d2f8c0;
  stroke: none;
},
#crops {
  fill: #fcf8d8;
  stroke: none;
}
"""

for i in range(256):
    blue  = hex(int(256 - i)).split('x')[1].zfill(2)
    green = hex(int(256 - i)).split('x')[1].zfill(2)
    color = '#ff%s%s' % (green, blue)

    code += """
#zipcodes[Fullposition=%(pos)s] {
    fill: %(color)s;
}
""" % dict(pos = i, color = color)

open('intellidata/static/geo/maps.css', 'w').write(code)
